% Auto-generated by stereoCalibrator app on 02-Dec-2025
%-------------------------------------------------------


% Define images to process
imageFileNames1 = {'C:\Users\student\Desktop\folderepoze_swea_camera\dreapta\WIN_20251202_14_33_10_Pro.jpg',...
    'C:\Users\student\Desktop\folderepoze_swea_camera\dreapta\WIN_20251202_14_33_13_Pro.jpg',...
    'C:\Users\student\Desktop\folderepoze_swea_camera\dreapta\WIN_20251202_14_33_18_Pro.jpg',...
    'C:\Users\student\Desktop\folderepoze_swea_camera\dreapta\WIN_20251202_14_35_38_Pro.jpg',...
    };
imageFileNames2 = {'C:\Users\student\Desktop\folderepoze_swea_camera\stanga\WIN_20251202_14_32_17_Pro.jpg',...
    'C:\Users\student\Desktop\folderepoze_swea_camera\stanga\WIN_20251202_14_32_23_Pro.jpg',...
    'C:\Users\student\Desktop\folderepoze_swea_camera\stanga\WIN_20251202_14_32_27_Pro.jpg',...
    'C:\Users\student\Desktop\folderepoze_swea_camera\stanga\WIN_20251202_14_35_13_Pro.jpg',...
    };

% Detect calibration pattern in images
detector = vision.calibration.stereo.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames1, imageFileNames2);

% Generate world coordinates for the planar patten keypoints
squareSize = 24;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Read one of the images from the first stereo pair
I1 = imread(imageFileNames1{1});
[mrows, ncols, ~] = size(I1);

% Calibrate the camera
[stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(stereoParams);

% Visualize pattern locations
h2=figure; showExtrinsics(stereoParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, stereoParams);

% You can use the calibration data to rectify stereo images.
I2 = imread(imageFileNames2{1});
[J1, J2, reprojectionMatrix] = rectifyStereoImages(I1, I2, stereoParams);

% See additional examples of how to use the calibration data.  At the prompt type:
showdemo('StereoCalibrationAndSceneReconstructionExample')
 showdemo('DepthEstimationFromStereoVideoExample')
